In [1]:
#importing the numpy module
import numpy as np

In [2]:
#create an array object
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
#accessing the element
a[0]

1

In [5]:
a[1]

2

In [6]:
#comparing numpy array with python list
import time 
import sys

In [7]:
l=range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [8]:
array=np.arange(1000)
print(array.size*array.itemsize)

4000


In [9]:
size=100000

l1=range(size)
l2=range(size)

a1=np.arange(size)
a2=np.arange(size)

#python list
start=time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print('python list took:',(time.time()-start)*1000)

#numpy array
result=a1+a2
print('numpy took:',(time.time()-start)*1000)

python list took: 32.94539451599121
numpy took: 35.904884338378906


# Basic array operation

In [10]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])

In [11]:
a1+a2

array([5, 7, 9])

In [12]:
a1-a2

array([-3, -3, -3])

In [13]:
a1*a2

array([ 4, 10, 18])

In [14]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [15]:
#create 1-dimensional array
a1=np.array([5,6,9])

In [16]:
a[1]

2

In [17]:
a[0]

1

In [18]:
#2-dimensional array
a=np.array([[1,2],[3,4],[5,6]])

In [19]:
#to find the dimension
a.ndim

2

In [20]:
a1.ndim

1

In [21]:
#to find the byte size
a.itemsize

4

In [22]:
#to find datatype
a.dtype

dtype('int32')

In [26]:
#initiaize array with float data type
#

In [27]:
a.ndim

2

In [28]:
a.itemsize

8

In [29]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [30]:
#to find the total number of elements
a.size

6

In [31]:
#to know about the dimension (like width and height)
a.shape

(3, 2)

In [32]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.complex)

In [33]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [34]:
#initialize all elements with zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
#initialize all elements with ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
l=range(5)

In [38]:
l

range(0, 5)

In [39]:
l[0]

0

In [40]:
l[3]

3

In [42]:
np.arange(1,5)

array([1, 2, 3, 4])

In [43]:
np.arange(1,5,2)

array([1, 3])

In [44]:
np.linspace(1,5,10) #generate 10 number between 1 and 5 which are linearly spaced.

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [45]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [46]:
a=np.array([[1,2],[3,4],[5,6]])

In [47]:
a.shape

(3, 2)

In [48]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [50]:
a.ravel() #ravel will flatten it and make it one dimension

array([1, 2, 3, 4, 5, 6])

In [51]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

# Some mathematical functions

In [53]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
a.min()

1

In [55]:
a.max()

6

In [56]:
a.sum()

21

In [57]:
#sum all elements in rows together
a.sum(axis=1)

array([ 3,  7, 11])

In [58]:
#sum all elements in columns together
a.sum(axis=1)

array([ 3,  7, 11])

In [59]:
#to find the square root
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [61]:
#to find standard deviation
np.std(a)

1.707825127659933

In [64]:
#add two different array
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])\

a+b

array([[ 6,  8],
       [10, 12]])

In [65]:
a-b

array([[-4, -4],
       [-4, -4]])

In [66]:
a*b

array([[ 5, 12],
       [21, 32]])

In [67]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [69]:
#matrix product of the two individual matrixs
a.dot(b)

array([[19, 22],
       [43, 50]])

# Slicing/stacking and indexing with boolean arrays

In [70]:
n=[6,7,8]

In [71]:
n[0:2]

[6, 7]

In [72]:
n[-1]

8

In [73]:
a=np.array([6,7,8])

In [74]:
a[0:2]

array([6, 7])

In [75]:
a[-1]

8

In [76]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])

In [77]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [78]:
a.ndim

2

In [79]:
a[1,2]

3

In [80]:
a[0:2,2]

array([8, 3])

In [81]:
a[-1]

array([9, 3, 2])

In [82]:
a[-1,0:2]

array([9, 3])

In [83]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [84]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [85]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [86]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [87]:
a=np.arange(6).reshape(3,2)

In [93]:
b=np.arange(6,12).reshape(3,2)

In [94]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [95]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [96]:
#verticle stacking
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [97]:
#horizontal stacking
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [98]:
#horizontal split
a=np.arange(30).reshape(2,15)

In [99]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [100]:
result=np.hsplit(a,3)

In [101]:
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [102]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [103]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [104]:
#verticle split
result=np.vsplit(a,2)

In [105]:
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [106]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [108]:
a=np.arange(12).reshape(3,4)

In [109]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
b=a>4

In [111]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [112]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [113]:
a[b]=-1

In [114]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

# Read/Write Text files

In [115]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]],np.int32)

In [116]:
np.savetxt('text.txt',x)

In [117]:
#for reading the file
y=np.loadtxt('text.txt')
print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# iterate numpy array using nditer

In [118]:
a=np.arange(12).reshape(3,4)

In [119]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Using normal for loop iteration

In [121]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


# For loop with flatten

In [122]:
for cell in a .flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


# C style ordering

In [123]:
#print row by row
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


# Fortan style ordering 

In [124]:
#print column by column
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


# external_loop

In [125]:
for x in np.nditer(a, flags=['external_loop'],order='F'):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


# Modify array values while iterating

In [126]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [127]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

# Iterate two broadcastable arrays concurrently

In [128]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [129]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
